=== HUHaoran1996/Exercise-Xml/tp1/movie.dtd
<!-- DTD created at Wed Nov 14 16:34:24 CET 2018 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT movies (movie+)>
<!ELEMENT movie (title,kind,duration,moviemaker,language,actors,yearofproduction,story,rating,schedules)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT moviemaker (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT actors (actor+)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT yearofproduction (#PCDATA)>
<!ELEMENT story (#PCDATA)>
<!ELEMENT rating (press,speces)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT speces (#PCDATA)>
<!ELEMENT schedules (schedule+)>
<!ELEMENT schedule (#PCDATA)>

<!ATTLIST movie id CDATA #REQUIRED>

<!ATTLIST moviemaker lang (en|fr) "en">

<!ATTLIST actor id CDATA #REQUIRED>

<!ATTLIST story lang (en|fr) "en">

<!ATTLIST schedule id CDATA #REQUIRED>

=== HUHaoran1996/Exercise-Xml/tp1/movies.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Wed Nov 14 15:11:17 CET 2018 -->

<?xml-stylesheet href="movie.css" type="text/css"?>

<!DOCTYPE movies SYSTEM "movie.dtd">
<movies>
	<movie id="1">
		<title>
	Les Brigades du Tigre
	</title>
		<kind>
	Thriller
	</kind>
		<duration>
	(2h 5min)
	</duration>
		<moviemaker lang="fr">
	Jérôme Cornuau
	</moviemaker>
		<language>
	VF(en  French)
	</language>
		<actors>
			<actor id="1">
		C.cornillac
		</actor>
			<actor id="2">
		D.Kruger		
		</actor>
			<actor id="3">
		E.Baer
		</actor>
		</actors>
		<yearofproduction>
		Year:2005
	</yearofproduction>
		<story lang="en">
		About the adventures of commissar Valentin and inspectors Terrasson and Pujol,
members of the " Brigades mobiles", special squad of the French police before
the first world war
	</story>
		<rating>
			<press>
			Press :3/5
	</press>
			<speces>
			Spectators :4/5
	</speces>
		</rating>
		<schedules>
			<schedule id="1">
		Wed, Sat : 14:00 | 16:40 | 19:40 | 22:10
		</schedule>
			<schedule id="2">
		Tue, Fri, Mon, Thu : 14:00 | 19:40 | 22:10
		</schedule>
			<schedule id="3">
		Sun : 10:20 | 14:00 | 16:40 | 20:20
		</schedule>
		</schedules>
	</movie>
	<movie id="2">
		<title>
	Avengers
	</title>
		<kind>
	super-heros 
	</kind>
		<duration>
	(2h 22min)
	</duration>
		<moviemaker lang="en">
	 Joss Whedon
	</moviemaker>
		<language>
	(en  Anglais)
	</language>
		<actors>
			<actor id="1">
		Robert Downey Jr
		</actor>
			<actor id="2">
		Chris Evans		
		</actor>
			<actor id="3">
		 Chris Hemsworth
		</actor>
			<actor id="4">
		 Scarlett Johansson	
		</actor>
		</actors>
		<yearofproduction>
		Year:2012
	</yearofproduction>
		<story lang="fr">
		 Il se base sur l'équipe de super-héros du même nom (Les Vengeurs en français) apparaissant dans le comic book publié par Marvel Comics et constitue le sixième film de l'univers cinématographique Marvel
	</story>
		<rating>
			<press>
			Press :3/5
	</press>
			<speces>
			Spectators :4/5
	</speces>
		</rating>
		<schedules>
			<schedule id="1">
		Wed, Sat : 14:00 | 16:40 | 19:40 | 22:10
		</schedule>
			<schedule id="2">
		Tue, Fri, Mon, Thu : 14:00 | 19:40 | 22:10
		</schedule>
			<schedule id="3">
		Sun : 10:20 | 14:00 | 16:40 | 20:20
		</schedule>
		</schedules>
	</movie>
</movies>
